#!/bin/bash

clear
echo 
echo -e "\e[1m Love You All..!!!"
apt update
apt upgrade -y
apt install figlet -y
figlet Basic Installation
apt install toilet -y
apt install cowsay -y
apt install nano -y
apt install cmatrix
gem install lolcat
echo $W "Installing requirements........"$G
apt-get install curl -y
apt-get install tor -y
apt-get install perl -y
apt-get install git -y
apt-get install hydra -y
apt-get install python -y
apt-get install python2 -y
apt-get install php -y
apt-get install nmap -y
apt-get install apache2 -y 
apt-get install cowsay -y
apt-get install ruby -y
figlet -f big Good Job!!! | lolcat
echo
echo -e "\e[1m MarMu is the Best..!!!"
echo
echo -e "\e[1m\e[32m Creation by :\e[33m MarMu (Myanmar)"
cmatrix

echo
exit
